### ISSUE TITLE
Path in utils.py

### ISSUE THREAD

**Issue by urobasa** [dipcore/mstar-bin-tool#10]
error
[i]     Unpacking LZO (Please be patient) unpacked/system.lzo -> unpacked/system.img
sh: 1: bin/linux-x86/lzop: not found

in ubuntu lzop path - /usr/bin/lzop

**Comment by dipcore** [comment]
Hey, just create a ```bin/linux-x86/``` folder and make links on all required binaries. ie ```ln -ls /usr/bin/lzop ./bin/linux-x86/```
