### ISSUE TITLE
Questions about extract_keys.py ？

### ISSUE THREAD

**Issue by goujibing** [dipcore/mstar-bin-tool#2]
Some of the KEY is not in the mboot file .And the <key bank offset> must be very accurate. How to determine key bank offset?

**Comment by dipcore** [comment]
look at the https://github.com/dipcore/mstar-bin-tool/blob/master/extract_keys.py There is a comments section which explains how to find the offset.

The easiest way is to open mboot.bin with any hex editor and do search by string "Mstar.Key.Bank" You should get two equal sections, the key bank and the key bank backup.
