### ISSUE TITLE
6 security vendors flagged this file as malicious in virustotal

### ISSUE THREAD

**Issue by fishso** [dipcore/mstar-bin-tool#28]
https://www.virustotal.com/gui/file/a9560123a284e5b9c38eee849d7eee0f1ecf07a80249e122f283f7e5fa67fa87/detection
![image](https://user-images.githubusercontent.com/10240813/207345599-1697012d-588a-43aa-9894-89bb5aa4b9e2.png)

**Comment by dipcore** [comment]
It appears that this file (alignment.exe) is encrypted, as you can see in the analysis description (this does not mean that it contains a trojan). But in fact the file was extracted from the official MStar tool. 

NB You can even find the source code of the tool, if you have enough desire to do so. And build it yourself.
