### ISSUE TITLE
getting below error message

### ISSUE THREAD

**Issue by sachin0606** [dipcore/mstar-bin-tool#3]
![image](https://user-images.githubusercontent.com/14800089/47762829-3b479000-dce4-11e8-965f-e22c9d0ddbd1.png)

please help me to solve

**Comment by 283330601** [comment]
i think you maybe need to install python 3 instead of your python 2. 
when i installed python 3.7.1 then the problem is solved.

**Comment by 283330601** [comment]
> ![image](https://user-images.githubusercontent.com/14800089/47762829-3b479000-dce4-11e8-965f-e22c9d0ddbd1.png)
> 
> please help me to solve

i think you maybe need to install python 3 instead of your python 2.
when i installed python 3.7.1 then the problem is solved.

**Comment by 283330601** [comment]
How to solve this?

C:\mstar-bin-tool-master>unpack.py 1.bin
[i] Analizing header ...
[i] Saving header script to unpacked\~header_script ...
[i] Parsing script ...
Traceback (most recent call last):
  File "C:\mstar-bin-tool-master\unpack.py", line 96, in
<module>
    line = utils.applyEnv(line, env)
AttributeError: module 'utils' has no attribute 'applyEnv'

**Comment by dipcore** [comment]
Use the latest version, it's in utils.py line 148

**Comment by dipcore** [comment]
tclconfig.img is most likely ext4 image. Just use any tool to pack/unpack ext4 images or just mount it in linux.
My tools are for mstar bin images only.

**Comment by sung3moon** [comment]
hello i have a qusetion.
i have same issue
how can i fix the error 'utf-8'
can you give me a example? how to apply setenv
where can i put the code to?
plz give me example the code

# Apply env variable to line, i.e.
# setenv imageSize 0x13800
# setenv imageOffset 0x4000
# filepartload 0x20200000 LetvUpgrade938.bin $(imageOffset) $(imageSize)
# So we replace it to filepartload 0x20200000 LetvUpgrade938.bin 0x4000 0x13800
def applyEnv(line, env):
	keys = re.findall('\$\((\w+)\)', line)
	for key in keys:
		if key in env and env[key]:
			line = line.replace("$({})".format(key), env[key])
	return line

**Comment by V7619** [comment]
[i] Analizing header ...
Traceback (most recent call last):
  File "unpack.py", line 42, in <module>
    offset = header.find('\xff'.encode(encoding='iso-8859-1'))
UnicodeDecodeError: 'ascii' codec can't decode

**Comment by jason0505** [comment]
i have same issue
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 4097
installed other verision not work
